### ISSUE TITLE
Custom Validator Duplicate Entry Error when Resubmitting the Form :)

### ISSUE THREAD

**Issue by rbrahul** [thedevsaddam/govalidator#23]
Hi Saddam,
I am trying to create a custom validation rule. It works great when I submit the form first time. But after changing the value for form field when I resubmit the again it shows me: 

```
 http: panic serving [::1]:57565: validator: password_confirmed is already defined in rules
goroutine 26 [running]:
net/http.(*conn).serve.func1(0xc4203b6000)
        /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x13ecf40, 0xc420268c80)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/thedevsaddam/govalidator.AddCustomRule(0x1473f19, 0x12, 0xc420268c60)
        /Users/rbrahul/go/src/github.com/thedevsaddam/govalidator/rules.go:22 +0x154
main.createUser(0x1671740, 0xc42039a0e0, 0xc42026bd00)
        /Users/rbrahul/Projects/go/src/users/userHandlers.go:364 +0xca
net/http.HandlerFunc.ServeHTTP(0x148b688, 0x1671740, 0xc42039a0e0, 0xc42026bd00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc42031e000, 0x1671740, 0xc42039a0e0, 0xc42026bd00)
        /Users/rbrahul/go/src/github.com/gorilla/mux/mux.go:159 +0xed
net/http.serverHandler.ServeHTTP(0xc420296a90, 0x1671740, 0xc42039a0e0, 0xc42026bb00)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4203b6000, 0x1671e00, 0xc420259dc0)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288
```

And here is my source code:

```
...
govalidator.AddCustomRule("password_confirmed", func(field string, rule string, message string, value interface{}) error {
		fmt.Println("Val ", req.PostFormValue(field))
		if req.PostFormValue(field) != req.PostFormValue("password") {
			return fmt.Errorf("Field %s is miss matched with password", field)
		}
		return nil
	})
...
```

**Comment by thedevsaddam** [comment]
@rbrahul Please add the custom rules inside `init` function or inside `sync.One` so that same rule does not register twice, I think you already figured it out bhai :)
