### ISSUE TITLE
reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by s4kibs4mi** [thedevsaddam/govalidator#4]
```
2017/10/14 21:53:24 http: panic serving [::1]:51539: reflect: call of reflect.Value.Type on zero Value
goroutine 50 [running]:
net/http.(*conn).serve.func1(0xc420175680)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1697 +0xd0
panic(0x14ae000, 0xc420228820)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9/libexec/src/reflect/value.go:1688 +0x1a3
github.com/thedevsaddam/govalidator.(*roller).traverseStruct(0xc42004f7c8, 0x1533a00, 0xc42012a640)
	/Users/s4kib/go/src/github.com/thedevsaddam/govalidator/roller.go:114 +0x772
github.com/thedevsaddam/govalidator.(*roller).traverseStruct(0xc42004f7c8, 0x14f5020, 0xc42012a630)
	/Users/s4kib/go/src/github.com/thedevsaddam/govalidator/roller.go:106 +0x30a
github.com/thedevsaddam/govalidator.(*roller).traverseStruct(0xc42004f7c8, 0x1504620, 0xc42012a630)
	/Users/s4kib/go/src/github.com/thedevsaddam/govalidator/roller.go:106 +0x30a
github.com/thedevsaddam/govalidator.(*roller).start(0xc42004f7c8, 0x150df40, 0xc42012a5a0)
	/Users/s4kib/go/src/github.com/thedevsaddam/govalidator/roller.go:40 +0x310
github.com/thedevsaddam/govalidator.(*Validator).ValidateJSON(0xc42004fa20, 0x0)
	/Users/s4kib/go/src/github.com/thedevsaddam/govalidator/validator.go:146 +0x2a5
```

**Comment by thedevsaddam** [comment]
@s4kibs4mi Could you please provide the example of data structure for this bug.

**Comment by s4kibs4mi** [comment]
```
type User struct {
	bongo.DocumentBase `json:"-",bson:",inline"`
	Hash     string    `json:"hash"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Level    int       `json:"level"`
}
```
`bongo.DocumentBase` is embedded structure of [bongo odm](https://github.com/go-bongo/bongo)
